# Generated by Django 2.2.5 on 2019-09-24 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190924_1231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
