# Generated by Django 2.2.5 on 2019-09-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Please enter first name here ', max_length=20)),
                ('first_name', models.CharField(help_text='Please enter first name here ', max_length=20)),
                ('last_name', models.CharField(help_text='Please enter first name here ', max_length=20)),
                ('email', models.EmailField(help_text='Please enter first name here ', max_length=50)),
                ('phone_number', models.IntegerField(help_text='Please enter first name here ', max_length=10)),
                ('password', models.CharField(help_text='Please enter first name here ', max_length=20)),
            ],
        ),
    ]
