# Generated by Django 2.2.5 on 2019-09-28 06:43

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20190927_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ram', models.CharField(max_length=10)),
            ],
            managers=[
                ('laptop', django.db.models.manager.Manager()),
            ],
        ),
    ]
